name: Deploy Scraps

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            client/package-lock.json

      - name: Create client env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > client/.env

      - name: Create server env file
        run: |
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > server/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> server/.env
          echo "CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }}" >> server/.env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> server/.env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> server/.env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> server/.env
          echo "APP_URL=${{ secrets.APP_URL }}" >> server/.env
          echo "PORT=${{ secrets.PORT }}" >> server/.env

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm ci

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      - name: Deploy frontend to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "client/dist/*"
          target: "/var/www/POOSD_MERN_Project/client/dist"
          strip_components: 2
          rm: true

      - name: Deploy backend files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "server/*"
          target: "/var/www/POOSD_MERN_Project/server"
          overwrite: true

      - name: Install dependencies and restart server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/POOSD_MERN_Project/server
            npm ci --production
            pm2 reload mern-backend --update-env || pm2 start server.js --name "mern-backend"
            pm2 save
            nginx -s reload